// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXCEkYPiqtj26eTtnWaNSlzbv98GIZ-z8',
    appId: '1:705709936353:web:0b7cd4cf3a28e41fa2b1a0',
    messagingSenderId: '705709936353',
    projectId: 'talktostranger-ed3ac',
    authDomain: 'talktostranger-ed3ac.firebaseapp.com',
    storageBucket: 'talktostranger-ed3ac.appspot.com',
    measurementId: 'G-JJF82TWN1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7J4b2X1efLzL8-IwqgC5uU6nMnZpHpSQ',
    appId: '1:705709936353:android:4144ca9071a9c43aa2b1a0',
    messagingSenderId: '705709936353',
    projectId: 'talktostranger-ed3ac',
    storageBucket: 'talktostranger-ed3ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfyhxPr55NabPYZOYzM3zVQhWI0B_1n7w',
    appId: '1:705709936353:ios:8c028cb667600cfda2b1a0',
    messagingSenderId: '705709936353',
    projectId: 'talktostranger-ed3ac',
    storageBucket: 'talktostranger-ed3ac.appspot.com',
    androidClientId: '705709936353-f859h4bfk31l9vkt4qe8actbrr4f4u08.apps.googleusercontent.com',
    iosClientId: '705709936353-j7npjqj91q6dc3bid00ci6vpvva8eqv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebrtcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfyhxPr55NabPYZOYzM3zVQhWI0B_1n7w',
    appId: '1:705709936353:ios:8c028cb667600cfda2b1a0',
    messagingSenderId: '705709936353',
    projectId: 'talktostranger-ed3ac',
    storageBucket: 'talktostranger-ed3ac.appspot.com',
    androidClientId: '705709936353-f859h4bfk31l9vkt4qe8actbrr4f4u08.apps.googleusercontent.com',
    iosClientId: '705709936353-j7npjqj91q6dc3bid00ci6vpvva8eqv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebrtcApp',
  );
}
